# Generated by Django 2.0.4 on 2018-04-09 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180409_1428'),
        ('users', '0006_auto_20180409_0915'),
    ]

    operations = [
    ]
