# Generated by Django 2.0.4 on 2018-04-28 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180410_2232'),
        ('users', '0007_merge_20180409_2004'),
    ]

    operations = [
    ]
