# Generated by Django 2.0.4 on 2018-05-06 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_merge_20180428_1958'),
        ('users', '0008_merge_20180423_2158'),
    ]

    operations = [
    ]
