# Generated by Django 2.0.4 on 2018-05-06 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_merge_20180504_1628'),
        ('users', '0009_merge_20180506_1129'),
    ]

    operations = [
    ]
