# Generated by Django 2.0.3 on 2018-04-03 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20180402_1213'),
        ('articles', '0003_auto_20180325_1242'),
    ]

    operations = [
    ]
