# Generated by Django 2.0.3 on 2018-04-10 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_merge_20180403_1012'),
        ('articles', '0005_auto_20180404_2243'),
    ]

    operations = [
    ]
