# Generated by Django 2.0.4 on 2018-04-08 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20180404_2243'),
        ('articles', '0004_merge_20180403_1012'),
    ]

    operations = [
    ]
