# Generated by Django 2.0.4 on 2018-04-09 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_merge_20180409_1428'),
        ('articles', '0006_merge_20180408_2041'),
    ]

    operations = [
    ]
