# Generated by Django 2.0.3 on 2018-04-23 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_merge_20180410_2232'),
        ('articles', '0007_merge_20180409_2004'),
    ]

    operations = [
    ]
