# Generated by Django 2.0.4 on 2018-05-04 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_merge_20180423_2157'),
        ('articles', '0008_merge_20180428_1958'),
    ]

    operations = [
    ]
