# Generated by Django 2.0.3 on 2018-05-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_merge_20180506_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
